# Generated by Django 3.1.4 on 2021-05-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_gasto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_gasto',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'VARIABLE'), (1, 'FIJO')], default=0),
        ),
        migrations.AlterField(
            model_name='tipo_gasto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
