# Generated by Django 3.1.4 on 2021-05-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0002_remove_gasto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=9),
        ),
    ]
