# Generated by Django 3.1.4 on 2021-05-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pvp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=9, null=True),
        ),
    ]
