# Generated by Django 3.1.4 on 2021-05-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210519_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='p_venta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.51, max_digits=9, null=True),
        ),
    ]
