# Generated by Django 3.1.4 on 2021-05-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='devolucion',
        ),
    ]
