# Generated by Django 3.1.4 on 2021-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_auto_20210331_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='compra',
            name='comprobante',
            field=models.IntegerField(default=1),
        ),
    ]
