# Generated by Django 3.1.4 on 2021-05-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_auto_20210522_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comprobante',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
