# Generated by Django 3.1.4 on 2021-06-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_auto_20210522_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='inventario_estado',
            new_name='inv_estado',
        ),
    ]
