# Generated by Django 3.1.4 on 2021-06-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20210128_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
    ]
